name: "Compile .ts into .js"
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
jobs:
  compile:
    if: ${{ github.event.label.name == 'compile'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all branches

      - name: Print Label
        run: |
          echo "New Labels"

          echo "${{github.ref}}"
          echo "${{github.head_ref}}"
          echo "${{github.base_ref}}"
      - name: install typescript
        run: npm install typescript

      - name:
        run: npm install typescript

      - name: Pass If Git Add, Commit, Push
        run: |
          git branch
          git config --global user.email "${{ github.actor }}@github.bot"
          git config --global user.name "${{ github.actor }}"
          git checkout -t origin/"${{ github.base_ref}}"

          npx tsc
          git add .

          if [ "$(git diff --cached --name-only)" ]; then
            echo "Staged changes detected. Committing and pushing..."
            git commit -m "chore: pre-merged compile .ts"
            git push origin "${{ github.base_ref }}"

          else
            echo "No staged status file"
          fi

# git branch
# git checkout -t origin/"${{ github.head_ref}}"
# git config --global user.email "${{ github.event.sender.email}}"
# git config --global user.name "${{ github.event.sender.name}}"

# npx tsc
# git add .

# if [ "$(git diff --cached --name-only)" ]; then
#   echo "Staged changes detected. Committing and pushing..."
#   git commit -m "chore: pre-merged compile .ts"
#   git push origin "${{ github.head_ref }}"

# else
#   echo "No staged status file"
# fi

