name: "Compile .ts into .js"

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
jobs:
  compile:
    if: ${{ github.event.label.name == 'compile'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all branches

      - name: Print Label
        run: |
          echo "New Labels"
          echo "${{github.event.label.name}}"

      - name: Check Staged File and Commit Pushing
        run: |
          git branch
          git checkout -t origin/"${{ github.head_ref}}"
          git config --global user.email "${{ github.event.sender.email}}"
          git config --global user.name "${{ github.event.sender.name}}"

      - name: Compile .ts
        run: npx tsc

      - name: Pass If Git Add, Commit, Push
        run: |
          git add dist
          if [ "$(git diff --cached --name--only)" ]; then
            echo "Staged changes detected. Committing and pushing..."
            git commit -m "chore: pre-merged compile .ts"
            git push origin "${{ github.head_ref }}"
